add draft with styleguide.md
2gis/on-premise-helm-charts pull request #137
Opened 2022-08-17 03:46 UTC by ksidenko

2022-08-17 05:47 UTC, Fullmetal8ender commented on styleguide.md
> +* Для каждой настройки должен стоять дефолт, как его ставить:
Не для каждой. Есть ряд критичных настроек, которые клиент должен выставить вдумчиво. Например суффикс в касандре. Если выставить дефолт - клиент про него не узнает, или забудет и в конечном итоге себе что-нибудь сломает, т.к. суффикс служит защитой от перетирания кейсейсов, когда бой и тест используют одну касандру.

Такие переменные должны быть required и при пустом значении возвращать понятный текст ошибки

2022-08-17 05:47 UTC, Fullmetal8ender commented on styleguide.md
> +* Пример: restrictions_api_url: 'http://navi-restrictions.host'
Вот это пример сомнительного варианта.
Клиент не укажет это поле, у него подеплоится и не будет работать.
Диагностика в онпреме как правило никакая (будет ошибка типа `not found: 3(NXDOMAIN)` )

А если тут оставить пустое значение и сделать поле required, то при деплое клиент получит понятное сообщение об ошибке

2022-08-17 06:00 UTC, denrockit requested changes

2022-08-17 06:34 UTC, Fullmetal8ender commented on styleguide.md
> +* Для каждого блока настроек всегда должна быть ссылка на официальную документацию (VPA, HPA, PDB, ...)
Я тут согласен с Дэном. Достаточно же написать "смотри оф. доку по настройке или типа того". У нас все таки не детский сад. Да и ссылки устареют очень быстро. 
Хотя можно поглядеть как в других хелмах делают

2022-08-17 07:37 UTC, i-bogomazov commented on styleguide.md
> +# В переменных, где предполагается конечный список значений, всегда его явно перечисляем, дефолт error
`error` это из примера ниже?

2022-08-17 07:37 UTC, i-bogomazov commented on styleguide.md
> +  * настройка должна быть типовой +- типого использования сервиса у любого партнера
"типовой +- типого" здесь что-то стоит переписать

2022-08-17 07:37 UTC, i-bogomazov commented on styleguide.md
> +* Одинаковые настройки назваем везде одинаково.
называем

2022-08-17 07:37 UTC, i-bogomazov commented on styleguide.md
> +  * enable — когда опция включена / выключена. Дефолт: чаще всего false
используется в форме `enabled` (с `d`)

2022-08-17 07:37 UTC, i-bogomazov commented on styleguide.md
> +    * serviceAccount → sa
надо заметить, что в стандартном шаблоне helm `serviceAccount` без сокращений ( https://github.com/helm/helm/blob/main/pkg/chartutil/create.go#L122 ), по-моему лучше на это ориентироваться

2022-08-17 07:37 UTC, i-bogomazov commented on styleguide.md
> +  * Ingress описывем только host и cсылку на официальную документацию
хотелось бы видеть ещё `ingress.enabled` явно в readme

2022-08-17 07:37 UTC, i-bogomazov commented on styleguide.md
> +  * S3 - https://github.com/2gis/on-premise-helm-charts/pull/124/files#diff-439bd87592d0ae6027750dd8342d3e2bef43c01e3b68e5330049f0076eb23af6R162
@dbelyaev-nsk или на `storage` переделывать?

2022-08-17 07:37 UTC, i-bogomazov commented on styleguide.md
> +# ToDo. Примеры типовых шаблонов yaml
перекликается с оф стайл-гайдом, наверно, стоит прилинковать: https://helm.sh/docs/chart_best_practices/templates/#structure-of-templates

2022-08-17 07:37 UTC, i-bogomazov commented on styleguide.md
> +* Ресурсы всегда пишем с дефолтами, на которых сервис запуститься на dev контуре
запустится

2022-08-17 08:18 UTC, i-bogomazov commented on styleguide.md
> +  * S3 - https://github.com/2gis/on-premise-helm-charts/pull/124/files#diff-439bd87592d0ae6027750dd8342d3e2bef43c01e3b68e5330049f0076eb23af6R162
неправильно поменшенил, @Fullmetal8ender

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +# В переменных, где предполагается конечный список значений, всегда его явно перечисляем, дефолт error
переписал

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +* Пример: LOG_LEVEL - error, warn, info, bebug
поправил

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +* Для каждого блока настроек всегда должна быть ссылка на официальную документацию (VPA, HPA, PDB, ...)
Мне кажется, что тут нет смысла спорить, т.к. по факту это уже и так сделано см. https://github.com/2gis/on-premise-helm-charts/tree/master/charts/mapgl-js-api#kubernetes-ingress-settings
Насчет детского сада. Практика показывает, что может быть и так, мы не можем на это повлиять на уровень вкалификации девопса патнера. Поэтому наличие ссылки - минимально дешевый способ обезопасить себя на -1 такой себе вопрос в поддержке.

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +  * настройка должна быть типовой +- типого использования сервиса у любого партнера
угу, переписал

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +* Для каждой настройки должен стоять дефолт, как его ставить:
добавил исключение из правила

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +* Одинаковые настройки назваем везде одинаково.
поправил

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +  * enable — когда опция включена / выключена. Дефолт: чаще всего false
а вот тут у нас кто во что горазд, половина хелмов так, половина - так (((

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +    * serviceAccount → sa
Добавил исключения

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +  * Ingress описывем только host и cсылку на официальную документацию
Точно? А зачем?

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +* Ресурсы всегда пишем с дефолтами, на которых сервис запуститься на dev контуре
ok

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +  * S3 - https://github.com/2gis/on-premise-helm-charts/pull/124/files#diff-439bd87592d0ae6027750dd8342d3e2bef43c01e3b68e5330049f0076eb23af6R162
А зачем переименовывать?

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +# ToDo. Примеры типовых шаблонов yaml
добавил в начало ссылку

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +* serviceaccount.yaml -
serviceaccount добавил в исключение. А так, предлагаю нейминг файлов оставить как тут описаны, т.е. только совсем длинные названия сокращать.

2022-08-18 06:25 UTC, ksidenko commented on styleguide.md
> +* Пример: restrictions_api_url: 'http://navi-restrictions.host'
здесь я преследовал другую проблему,  чтобы читая чарт уже без доп описания было понятно на какой сервис по смыслу нужно настроиться. 
Пример: чтобы у catalog-а было написано не абстрактный localhost, а что-то более приближенное к реальности
```
search:
    url: http://localhost:80
```
а 
```
search:
    url: http://search.host
```

2022-08-18 08:32 UTC, i-bogomazov commented on styleguide.md
> +  * Ingress описывем только host и cсылку на официальную документацию
потому что иначе в readme попадает, что есть блок ingress и у него есть дефолтный хост, хотя по факту ingress отключен

2022-08-18 08:35 UTC, i-bogomazov commented on styleguide.md
> +  * S3 - https://github.com/2gis/on-premise-helm-charts/pull/124/files#diff-439bd87592d0ae6027750dd8342d3e2bef43c01e3b68e5330049f0076eb23af6R162
потому что есть ещё форма со storage: https://github.com/2gis/on-premise-helm-charts/blob/8c042a31e958a0f947cf2d9b84574551d5e0668a/charts/navi-castle/values.yaml#L5

2022-08-18 08:39 UTC, i-bogomazov commented on styleguide.md
> +  * enable — когда опция включена / выключена. Дефолт: чаще всего false
судя по публичному репозиторию https://artifacthub.io/packages/search форма `enabled` единственная, `enable` встречается только как префикс - `enableHttps`, например

2022-08-18 08:56 UTC, ksidenko commented on styleguide.md
> +  * enable — когда опция включена / выключена. Дефолт: чаще всего false
Ты прав. 
Я еще так поискал https://github.com/2gis/on-premise-helm-charts/search?q=enable&type=code и нашел 1 косяк  https://github.com/2gis/on-premise-helm-charts/blob/master/charts/navi-back/values.yaml#L94

в https://github.com/2gis/on-premise-helm-charts/pull/124/files#r948835823 попросил поправить

2022-08-18 09:01 UTC, ksidenko commented on styleguide.md
> +  * S3 - https://github.com/2gis/on-premise-helm-charts/pull/124/files#diff-439bd87592d0ae6027750dd8342d3e2bef43c01e3b68e5330049f0076eb23af6R162
там же он не только с S3 работает, но и может на файлуху писать, вот и обобщенное название. https://docs.2gis.com/en/on-premise/dgctl#nav-lvl1--Configuration_file_structure 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/8588439/185355620-8cfba13d-bd7b-4f53-a553-35050db177fc.png">

2022-08-18 09:02 UTC, ksidenko commented on styleguide.md
> +  * S3 - https://github.com/2gis/on-premise-helm-charts/pull/124/files#diff-439bd87592d0ae6027750dd8342d3e2bef43c01e3b68e5330049f0076eb23af6R162
хотя я засомневался, это же не совсем оно. @Fullmetal8ender че думаешь?

2022-08-18 09:05 UTC, ksidenko commented on styleguide.md
> +  * Ingress описывем только host и cсылку на официальную документацию
согласен, внес правку

2022-08-18 15:01 UTC, ksidenko commented on styleguide.md
> +* Пример: restrictions_api_url: 'http://navi-restrictions.host'
Вот более наглядный пример, где говорящий хост сходу подсказывает связь сервисов:

https://docs.2gis.com/ru/on-premise/navigation/overview#nav-lvl2--Distance_Matrix_Async_API-1
```
dm:
    citiesUrl: 'http://navi-castle.host/cities.conf'
```

2022-08-19 09:20 UTC, andkazakov commented on styleguide.md
> +* Для каждой настройки должен стоять дефолт, как его ставить:
а давайте про required прям закрепим?

2022-08-19 12:38 UTC, ksidenko commented on styleguide.md
> +* Для каждой настройки должен стоять дефолт, как его ставить:
сделал

2022-08-22 07:52 UTC, documentat-alibaev commented on styleguide.md
> +* Для каждой настройки должен стоять дефолт, как его ставить:
Может, ещё пояснить, что переменные без дефолта нужно описывать через `@extra`? Или это очевидно?

2022-08-22 07:52 UTC, documentat-alibaev commented on styleguide.md
> +  * группы настроек тоже называем одинаково (сокращенно)
Мне кажется, эти примеры слишком сильно привязаны к нынешнему состоянию, а не желаемому, и поэтому при перечитывании спустя какое-то время могут оказаться непонятными. Предлагаю подстраховать, заменив стрелочки на более однозначные формулировки: «не autoscaling.enabled, а hpa.enabled».

2022-08-22 07:52 UTC, documentat-alibaev commented on styleguide.md
> +      * ingress не сокращаем, описывем только enabled, host и cсылку на официальную документацию
Может, лучше дать ссылку на пример правильного описанного `ingress` в одном из чартов?

2022-08-22 07:52 UTC, documentat-alibaev commented on styleguide.md
> +  * keys
Т.е. всякие блоки `api` будут переименованы? Или это не универсальное правило?

А что делать с чартами, в которых есть отдельные `api` и `admin`, хотя оба они вроде как логически часть одного «сервиса»?

2022-08-22 07:52 UTC, documentat-alibaev commented on styleguide.md
> +  * restrictions_api_url: 'http://navi-restrictions.host'
А протокол везде `http`? Не лучше ли это уточнить? Или это как-то само собой следует из того, как сервисы взаимодействуют? (типа, `https` невозможен?)

2022-08-22 09:24 UTC, documentat-alibaev commented on styleguide.md
> +  * исключение составляет настройка, которая критично повлияет на сервис, при не правильном указании, для такой ставим визуальную отметку **required** :
Почему бы не описывать такие настройки через `@extra`, т.е. без реального добавления параметра в values (но с проверкой где-то в темплейтах)? Чтобы для развёртывания _пришлось_ осознанно добавить параметр.

2022-08-23 05:01 UTC, ksidenko commented on styleguide.md
> +* Для каждой настройки должен стоять дефолт, как его ставить:
дописал

2022-08-23 05:06 UTC, ksidenko commented on styleguide.md
> +      * ingress не сокращаем, описывем только enabled, host и cсылку на официальную документацию
Да, нужно будет заполнять по ходу реального написания в хелмах

2022-08-23 05:06 UTC, dekhtyarev commented on styleguide.md
> +     * например, суффикс в касандре для Tiles API. Если выставить дефолт, то клиент про него не узнает, или забудет и в конечном итоге себе что-нибудь сломает, т.к. суффикс служит защитой от перетира
```suggestion
     * например, суффикс в Cassandra для Tiles API. Если выставить дефолт, то клиент про него не узнает, или забудет и в конечном итоге себе что-нибудь сломает, т.к. суффикс служит защитой от перетирания кейсейсов, когда бой и тест используют одну касандру.
```

2022-08-23 05:06 UTC, dekhtyarev commented on styleguide.md
> +* serviceaccount.yaml -
А почему наоборот полные названия не писать? Чьи байты мы экономим?

2022-08-23 05:06 UTC, dekhtyarev commented on styleguide.md
> +  * restrictions_api_url: 'http://navi-restrictions.host'
http конечно проще для тестового локального контура.
Но придётся поддерживать оба метода и внутри приложений прошерстить, чтобы не было принудительных редиректов на https , а просто использовалась {scheme}. 

Если есть необходимость в тестовом контуре - тогда дефолт это http, да.

2022-08-23 05:09 UTC, ksidenko commented on styleguide.md
> +  * keys
скорее всего нет. Речь про сущность **2ГИС Сервис**, а в глубине уже скорее всего как есть

2022-08-23 05:10 UTC, ksidenko commented on styleguide.md
> +  * restrictions_api_url: 'http://navi-restrictions.host'
Как дефолт http в примере норм, почти везде это работает. В карте поправим, чтобы тоже работало

2022-08-23 05:15 UTC, ksidenko commented on styleguide.md
> +# Следуем официальным [Best Practices](https://helm.sh/docs/chart_best_practices/templates/#structure-of-templates) написания helm чартов
поправил

2022-08-23 05:17 UTC, ksidenko commented on styleguide.md
> +* Для каждого блока настроек всегда должна быть ссылка на официальную документацию (VPA, HPA, PDB, ...)
Пока это выглядит так, что почти все ссылки уже настроены. Специально за ссылками, что во времени они могут отвалиться, не следим. Так что предлагаю оставить пока так.

2022-08-23 05:21 UTC, ksidenko commented on styleguide.md
> +* serviceaccount.yaml -
Да тут вопрос зачем? Можно и длинное везде писать.

2022-08-23 05:41 UTC, dekhtyarev commented on styleguide.md
> +* serviceaccount.yaml -
Минимум для нас, чтобы потом не было вопроса "а как вписать новый тип данных, полностью или сокращённо? А почему именно так?". 

При этом полные названия у k8s говорящие, сразу понимаешь о чём идёт речь. Вдруг кто-то из наших пользователей ещё не работал с некоторыми типами ресурсов и его могут смутить сокращения(минус 1 вопрос в нашу ТП)

2022-08-23 05:42 UTC, dekhtyarev commented on styleguide.md
> +* Для каждого блока настроек всегда должна быть ссылка на официальную документацию (VPA, HPA, PDB, ...)
Не следим - ОК. 

Если кто придёт с фидбеком - пусть сразу PR и создаёт.

2022-08-23 05:45 UTC, dekhtyarev approved these changes

2022-08-23 05:45 UTC, dekhtyarev commented on styleguide.md
> +  * postgres.host: http://postgres.host
postgres не по http :)

2022-08-23 05:45 UTC, ksidenko commented on styleguide.md
> +* serviceaccount.yaml -
Ок, поправлю, резонно

2022-08-23 06:30 UTC, ksidenko commented on styleguide.md
> +  * postgres.host: http://postgres.host
ой))) поправил

2022-08-24 03:20 UTC, ksidenko commented on styleguide.md
> +# Styleguide
Дополнение:
1. Для пустых значений используем одинарные кавычки:

* Пример: name: ''

3. Для строковых значений кавычки не используем

* пример: 
> repository: 2gis-on-premise/navi-back

@documentat-alibaev дополни плиз

2022-08-24 03:23 UTC, documentat-alibaev commented on styleguide.md
> +# Styleguide
Ок. Но, может, приписать явно «за исключением случаев, когда кавычки необходимы, например, когда внутри есть двоеточие»?

2022-08-24 03:34 UTC, ksidenko commented on styleguide.md
> +# Styleguide
Еще правки в соглашения:
* Команду по импорту данных в сервис **всегда** назваем **importer** - эталон [MapGL JS API Importer](https://github.com/2gis/on-premise-helm-charts/blob/master/charts/tiles-api/values.yaml#L258)
* Нейминг чарта должен соблюдаться в нейминге переменных чарта. 
  *   Пример для чарта pro-api: repository: 2gis-on-premise/urbigeo-importer → repository: 2gis-on-premise/pro-api-importer
* Не исползуем 2ГИС термины в названиях переменных
*   пример: bss → stat

2022-08-24 03:40 UTC, ksidenko commented on styleguide.md
> +# Styleguide
по мне так это лишнее.

2022-08-24 03:51 UTC, ksidenko commented on styleguide.md
> +
Когда сервис подключает другой сервис из On-Premise, то делаем это единообразно, пример:

1. Keys API
```
 keys-api:
    host: http://keys-api.host
    token: ''
    syncPeriod: 1m
```

2. Catalog API
```
catalog:
    host: http://catalog.host
    key: ''
```

3. Navigation APIs
```
navi:
    host: http://navi-back.host
    key: ''
```

2022-08-24 03:53 UTC, documentat-alibaev commented on styleguide.md
> +
Я не понял, о чём этот пример. Только о том, что имена `host` и `key` одинаковые?

2022-08-24 04:04 UTC, documentat-alibaev commented on styleguide.md
> +# Styleguide
Дополнил.

2022-08-24 04:14 UTC, ksidenko commented on styleguide.md
> +
1. Что есть секция с названием сервиса с неймингом из чарта
2. Что используется host  (а не URL, Domain, ...) и key (а не token,accessKey,...)

2022-08-24 04:16 UTC, ksidenko commented on styleguide.md
> +# Styleguide
только пока не запушил))

2022-08-24 04:17 UTC, documentat-alibaev commented on styleguide.md
> +# Styleguide
Ой, опять я в мёртвые ветки пушу!

Завести новый PR в styleguide? Или коммитить прямо сюда в styleguide?

2022-08-24 04:33 UTC, ksidenko commented on styleguide.md
> +# Styleguide
Прямо сюда комить

2022-08-24 04:37 UTC, documentat-alibaev commented on styleguide.md
> +# Styleguide
Тьфу, да у меня же нет прав сюда пушить. Запушил одноимённую ветку к себе форк: https://github.com/2gis/on-premise-helm-charts/compare/styleguide...documentat-alibaev:on-premise-helm-charts:styleguide

Тогда всё-таки сделать новый PR?

2022-08-24 04:47 UTC, ksidenko commented on styleguide.md
> +# Styleguide
Сделал тебе и Андрею права на репу

2022-08-24 04:48 UTC, documentat-alibaev commented on styleguide.md
> +# Styleguide
Запушил.

2022-08-24 04:48 UTC, documentat-alibaev commented on styleguide.md
> +
Добавил.

2022-08-24 05:36 UTC, ksidenko commented on styleguide.md
> +
Все три примера, они часто используемы, пусть явно будут прописаны

2022-08-24 05:58 UTC, documentat-alibaev commented on styleguide.md
> +
Добавил.

2022-08-26 02:00 UTC, ksidenko commented on styleguide.md
> +  * S3 - https://github.com/2gis/on-premise-helm-charts/pull/124/files#diff-439bd87592d0ae6027750dd8342d3e2bef43c01e3b68e5330049f0076eb23af6R162
@documentat-alibaev давай пункт https://helm.sh/docs/chart_best_practices/values/#naming-conventions добавим 
> Variable names should begin with a lowercase letter, and words should be separated with camelcase:
и вопрос в треде будет решен.

2022-08-26 02:38 UTC, ksidenko commented
@documentat-alibaev Давай еще добавим, что в примеры городов в дефолтах всегда используем Москву?
Чтобы нафиг потом Даммам удалить везде.

2022-08-26 07:28 UTC, documentat-alibaev commented on styleguide.md
> +  * S3 - https://github.com/2gis/on-premise-helm-charts/pull/124/files#diff-439bd87592d0ae6027750dd8342d3e2bef43c01e3b68e5330049f0076eb23af6R162
Добавил.

2022-08-29 03:06 UTC, merged