Catalog API. Data importer
2gis/on-premise-helm-charts pull request #144
Opened 2022-08-24 03:12 UTC by ksidenko

2022-08-31 12:09 UTC, denrockit approved these changes

2022-09-01 03:25 UTC, denrockit requested changes

2022-09-01 03:25 UTC, denrockit commented on charts/catalog-api/templates/importer/pvc.yaml
> +  name: {{ include "catalog.importer.name" . }}-pvc
Пока не поздно давайте ещё уберём из названия `-pvc`, это и так ресурс pvc и коллизии не будет.

2022-09-01 11:43 UTC, DemonNSK commented on charts/catalog-api/templates/importer/pvc.yaml
> +  name: {{ include "catalog.importer.name" . }}-pvc
убрали

2022-09-06 05:52 UTC, merged