cleaner schemes job
2gis/on-premise-helm-charts pull request #150
Opened 2022-09-05 15:05 UTC by DemonNSK

2022-09-08 05:00 UTC, denrockit requested changes

2022-09-08 05:00 UTC, denrockit commented on charts/catalog-api/values.yaml
> +    limit: 2
Наверное обозвать это поочевиднее типа versions или backups? Либо взять пример с джоб k8s, historyLimit там что-ли.

2022-09-08 07:05 UTC, DemonNSK commented on charts/catalog-api/templates/secret-cleaner-jobs.yaml
> +apiVersion: v1
а вот не сработало, падает с ошибкой, что не может secret найти

2022-09-08 07:06 UTC, DemonNSK commented on charts/catalog-api/values.yaml
> +    enabled: false
потому что у нас уже есть потребность не чистить, точнее даже не менять схемы

2022-09-08 07:10 UTC, DemonNSK commented on charts/catalog-api/values.yaml
> +    limit: 2
я взял пример с тайлов :)

2022-09-08 07:11 UTC, denrockit commented on charts/catalog-api/templates/secret-cleaner-jobs.yaml
> +apiVersion: v1
Может названием промахнулся? Надо `catalog.secret.deploys.name` брать.

2022-09-08 07:12 UTC, denrockit commented on charts/catalog-api/values.yaml
> +    enabled: false
Ну включить может по дефолту хотя б? Это ж каждый раз переопределять, если ты нормальный сценарий себе разворачиваешь.

2022-09-08 07:12 UTC, denrockit commented on charts/catalog-api/values.yaml
> +    enabled: false
У нас другой работы не предусмотрено на данный момент.

2022-09-08 07:21 UTC, DemonNSK commented on charts/catalog-api/templates/secret-cleaner-jobs.yaml
> +apiVersion: v1
т.к. секреты от деплоя не содержит нужных кредов для импортера, либо их тогда все туда пихать

2022-09-08 07:22 UTC, DemonNSK commented on charts/catalog-api/values.yaml
> +    enabled: false
включил по дефолту

2022-09-08 10:28 UTC, denrockit commented on charts/catalog-api/templates/importer/cleaner-job.yaml
> +{{- if .Values.importer.cleaner.enabled }}
А может этот файл утащим в `cleaner/job.yaml`? Логика структур до этого была сервис/приложение/задача это папка, всё что нужно для неё внутри, при этом называются по ресурсу k8s и обычно не пересекаются. В апи это например deployment, service, внутри тасок job и вот теперь pvc иногда. Секреты общие и вынесены отдельно.

2022-09-09 06:49 UTC, denrockit approved these changes

2022-09-22 08:29 UTC, merged