Configure Redis as external service
2gis/on-premise-helm-charts pull request #172
Opened 2022-09-30 09:12 UTC by pavelgopanenko

2022-09-30 10:26 UTC, keiqu approved these changes

2022-09-30 10:38 UTC, DemonNSK approved these changes

2022-09-30 12:10 UTC, denrockit requested changes

2022-09-30 12:10 UTC, denrockit commented on charts/keys/values.yaml
> +  host: redis
По гайдам вроде решено обзывать `redis.host`

2022-09-30 12:10 UTC, denrockit commented on charts/keys/templates/redis/statefulset.yaml
> +{{- if not .Values.redis.useExternalRedis }}
А конфигмап и сервис не закрыли флагом.

2022-10-04 04:06 UTC, denrockit approved these changes

2022-10-11 02:34 UTC, merged