Draft: IODEV-1542: tiles importer add minio secure mode
2gis/on-premise-helm-charts pull request #296
Opened 2023-08-21 14:48 UTC by IgorYurevich

`tiles-api` в поле `dgctlStorage.host` принимает как хост вида `host:port`, так и `shema://host:port` со схемой

2023-08-22 08:56 UTC, Bolodya1997 approved these changes

2023-08-23 12:24 UTC, Bolodya1997 commented on charts/tiles-api/README.md
> +| `dgctlStorage.host`      | S3 endpoint. Format: `http(s)://host:port`, scheme is optional, by default `http`.
Надо README обновить

2023-08-24 07:13 UTC, IgorYurevich commented on charts/tiles-api/README.md
> +| `dgctlStorage.host`      | S3 endpoint. Format: `http(s)://host:port`, scheme is optional, by default `http`.
Точно, спасибо за замечание, забыл перегенерировать ...

2023-08-24 10:52 UTC, Bolodya1997 approved these changes

2023-08-24 11:02 UTC, Bolodya1997 requested changes
Самое главное - забыли добавить это в конфигмапу :slightly_smiling_face:

2023-08-24 11:23 UTC, IgorYurevich commented
> Самое главное - забыли добавить это в конфигмапу 🙂

Добавил в конфигмапу, спасибо за замечание

2023-08-24 15:15 UTC, Fullmetal8ender approved these changes

2023-08-24 15:15 UTC, Fullmetal8ender commented on charts/tiles-api/values.yaml
> +  secure: false
Merging is blocked

2023-09-06 09:30 UTC, merged