Deploy secret as helm hook in keys chart
2gis/on-premise-helm-charts pull request #88
Opened 2022-06-10 21:23 UTC by keiqu

2022-06-23 13:56 UTC, Fullmetal8ender commented
То, что надо!

2022-07-05 10:28 UTC, denrockit requested changes

2022-07-05 10:28 UTC, denrockit commented on charts/keys/templates/secret-jobs.yaml
> +    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
`hook-succeeded`

А как стартанёт следующий хук джоба с миграцией, если этот удалится?

2022-07-05 10:28 UTC, denrockit commented on charts/keys/templates/secret-jobs.yaml
> +    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
С ролбеком пока не работали, не понятно надо ли. Миграции и импорты на данный момент в ролбеке не участвуют.

2022-07-06 08:02 UTC, keiqu commented on charts/keys/templates/secret-jobs.yaml
> +    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
Есть подозрение, что `hook-succeeded` вообще не работает для такого рода ресусрсов: ведь как понять успешно они выполнились или нет?) (делаю этот вывод, так как при деплое не мешало) Выпилю, чтобы глаза не мозолило.

2022-07-06 08:06 UTC, Fullmetal8ender commented on charts/keys/templates/secret-jobs.yaml
> +    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
Если выпилить, то секрет скорей всего останется. А сейчас он удаляется

2022-07-06 08:31 UTC, keiqu commented on charts/keys/templates/secret-jobs.yaml
> +    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
Вру. Верну назад, так как благодаря этому `hook-succeded` секрет удаляется, после того, как миграции прошли. Видимо, хелм смотрит на то, есть ли использующие его ресурсы или нет.

2022-07-06 10:12 UTC, denrockit approved these changes

2022-07-06 10:22 UTC, merged